<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BakMix levering ${trackingmail.orderId} tracking code</title>
</head>
<body>
<div style="margin-top: 10px">Hey ${trackingmail.customerName}, </div>
<br>
<div>Hierbij de tracking code van de levering!</div>
<br/>
<div>Tracking code: ${trackingmail.code}</div>
<br>
<div>Te gebruiken op <a href="${trackingmail.link}">${trackingmail.link}</a></div>
<br>
<div> Bedankt voor de bestelling en prettige dag!</div>
<div>BakMix.be</div>
</body>
</html>
